### PR TITLE
[Rosetta][Construction-API] fix constructing stacking tx using /preprocess

### LINKED ISSUE #674: [Rosetta][Construction-API][bug] constructing stacking tx using /preprocess not offline
when sending a stacking operation for constructing a transaction using /preprocess using the OFFLINE stacks API, it errors with
```
"error": "FetchError: request to http://127.0.0.1:20443/v2/contracts/interface/ST000000000000000000002AMW42H/pox failed, reason: connect ECONNREFUSED 127.0.0.1:20443" 
```
meaning that this is not offline as its trying to connect to the node.

/preprocess endpoint needs to be entirely offline, ie. cannot connect to the node.

I suspect it might be due to when creating a dummy stacking transaction: https://github.com/blockstack/stacks-blockchain-api/blob/master/src/api/routes/rosetta/construction.ts#L205-L214

### PR DESCRIPTION
**Pull request by asimm241**
## Description
This PR fixes the bug for rosetta `construction/preprocess`. The PR was making an api request to the node where it was supposed to work offline. 

fixes #674 

## Type of Change
- [ ] New feature
- [x] Bug fix
- [ ] API reference/documentation update
- [ ] Other

## Does this introduce a breaking change?
_NO_
## Are documentation updates required?
_NO_

## Checklist
- [ ] Code is commented where needed
- [ ] Unit test coverage for new or modified code paths
- [x] `npm run test` passes
- [ ] Changelog is updated
- [x]  @zone117x for review

### CODE REVIEW

File: src/api/routes/rosetta/construction.ts [hunk 1]
```diff
@@ -231,8 +229,7 @@ export function createRosettaConstructionRouter(db: DataStore, chainId: ChainID)
             noneCV(),
             noneCV(),
           ],
-          validateWithAbi: true,
-          network: getStacksNetwork(),
+          validateWithAbi: false,
```
Comment (zone117x) [inline src/api/routes/rosetta/construction.ts:232]: Think we need to add these to the offline-rosetta tests? Like I don't know off the top of my head of if `makeUnsignedContractCall` works without network when the `fee`/`nonce` are unspecified

Comment (asimm241) [reply src/api/routes/rosetta/construction.ts:232]: You're right,  It won't work I double-checked and It doesn't work without fee and network. 
So, I think I should provide a hardcoded fee here as well. 

Thanks for pointing that out.

Comment (zone117x) [reply src/api/routes/rosetta/construction.ts:236]: Fix looks good. We can merge if you've manually tested and verified the fix, but we should try to get this in the offline rosetta tests at some point.

Comment (asimm241) [reply src/api/routes/rosetta/construction.ts:236]: I have manually tested it with offline mode.
We do have a test for `/preprocess`, I don't know how to test this behaviour though. one idea that comes to mind is that we can disallow all network calls with `nock` but I don't know if it will work or not.

Comment (asimm241) [reply src/api/routes/rosetta/construction.ts:236]: @zone117x It works!. checkout the new commit!

**Review by zone117x — APPROVED** [review]
Thanks @asimm241!
