### PR TITLE
Fix subdomain name part

### LINKED ISSUE #554: Fix fqn issue in subdomains v1-import
**Describe the bug**
Subdomain name should be the name part instead of `fully qualified name` in v1-import script. 

**To Reproduce**
run v1-import script and check the `name` part of any `stacks 1.0` subdomains in the subdomain table, It will show the fully qualified name in the name field.

**Expected behavior**
There should be only the name part in the subdomain `name` field.

### PR DESCRIPTION
**Pull request by asimm241**
## Description
This PR addresses the small fix in the v1-import script, It assigns the name part to the `name` field of `subdomains` instead of `fqn`

fixes #554 

## Type of Change
- [ ] New feature
- [x] Bug fix
- [ ] API reference/documentation update
- [ ] Other

## Checklist
- [ ] Code is commented where needed
- [x] Unit test coverage for new or modified code paths
- [x] `npm run test` passes
- [ ] Changelog is updated
- [x] @zone117x for review

### CODE REVIEW

File: src/tests-bns/bns-integration-tests.ts [hunk 1]
```diff
@@ -25,6 +25,7 @@ import BigNum = require('bn.js');
 import { logger } from '../helpers';
 import { testnetKeys } from '../api/routes/debug';
 import { importV1 } from '../import-v1';
+import { query } from 'winston';
```
Comment (zone117x) [inline src/tests-bns/bns-integration-tests.ts:28]: Accidental import?

**Review by zone117x — APPROVED** [review]
Good catch, thanks @asimm241!
