### PR TITLE
Fix conflicting transaction hash for rosetta issue

### LINKED ISSUE #760: [Rosetta][Data-API] transaction with stx_unlock op has conflicting transaction hash
## Context
When Zondax initially added support in Rosetta API for stacking: #613 , "forged" transactions were created with `stx_unlock` operations because there are no actual on-chain transactions to show that accounts' tokens unlocked. This is due CB requiring balance changing events to be on-chain events otherwise addresses will be quarantined. 

So the solution was to  create a transaction to show these operations happened that only shows up in the Rosetta implementation and doesn't actually exist on-chain.

However, the implementation appears to use the transaction hash of the previous `stack_stx` operation for the account that shows up in the first `stx_unlock` operation's. This results in a transaction hash being used in two different blocks and causes issues because we can never actually return the "forged" transaction from `/block/transaction`.

### Simple Example
Account `ABC` stacked tokens (`stack_stx op` and `stx_lock`) in `block 5`. The transaction hash is `0x01`
Then, Account `ABC` unlocks tokens (`stx_unlock`) in `block 10`. The transaction hash for this "forged" transaction shows up also as `0x01`. When querying this transaction on `/block/transaction`, it shows the transaction that includes the `stack_stx` and `stx_lock` operations while the "forged" transaction is unable to be queried.

### Actual Example for Block 6926 in Testnet
```
      {
        "transaction_identifier": {
          "hash": "0x7cfac55147759a14d163bd96b89138df090dd730df5fa5c34a086011b5e9621e"
        },
        "operations": [
          {
            "operation_identifier": {
              "index": 0
            },
            "type": "stx_unlock",
            "status": "success",
            "account": {
              "address": "ST3C4YVASFG37P8E6210J9KHZJB4MF8ZRBQFKH41N"
            },
            "amount": {
              "value": "5140000000000",
              "currency": {
                "decimals": 6,
                "symbol": "STX"
              }
            },
            "metadata": {
              "tx_id": "0x7cfac55147759a14d163bd96b89138df090dd730df5fa5c34a086011b5e9621e"
            }
          },
          {
            "operation_identifier": {
              "index": 1
            },
            "type": "stx_unlock",
            "status": "success",
            "account": {
              "address": "ST3VR1JMSSCAXPQJSDKCCMX3TXB5RRYWBYK8HVK9S"
            },
            "amount": {
              "value": "6168000000000",
              "currency": {
                "decimals": 6,
                "symbol": "STX"
              }
            },
            "metadata": {
              "tx_id": "0xb078acd27a067d03ef87c3c112e74dc491665d1d7d28a49a2b0bae315ca227ef"
            }
          },
          {
            "operation_identifier": {
              "index": 2
            },
            "type": "stx_unlock",
            "status": "success",
            "account": {
              "address": "ST343J7DNE122AVCSC4HEK4MF871PW470ZV04CFXH"
            },
            "amount": {
              "value": "5500000000000",
              "currency": {
                "decimals": 6,
                "symbol": "STX"
              }
            },
            "metadata": {
              "tx_id": "0xac73fa29e0d9ef4c23ebf0867b6fdeb7ffa3ad249599f37ff9faa974259940e4"
            }
          },
          {
            "operation_identifier": {
              "index": 3
            },
            "type": "stx_unlock",
            "status": "success",
            "account": {
              "address": "ST319CF5WV77KYR1H3GT0GZ7B8Q4AQPY42ETP1VPF"
            },
            "amount": {
              "value": "5000000000000000",
              "currency": {
                "decimals": 6,
                "symbol": "STX"
              }
            },
            "metadata": {
              "tx_id": "0x86a70f4302c1f5a4e723bc5a1bbf21eaa34fc157160f08ed7105e83e0ada82bc"
            }
          },
          {
            "operation_identifier": {
              "index": 4
            },
            "type": "stx_unlock",
            "status": "success",
            "account": {
              "address": "ST221Z6TDTC5E0BYR2V624Q2ST6R0Q71T78WTAX6H"
            },
            "amount": {
              "value": "5000000000000000",
              "currency": {
                "decimals": 6,
                "symbol": "STX"
              }
            },
            "metadata": {
              "tx_id": "0x5d154237eb71d6ec3c8ca2a3aaad158485a90c1b14b841a4c5fcb6e3209105b6"
            }
          },
          {
            "operation_identifier": {
              "index": 5
            },
            "type": "stx_unlock",
            "status": "success",
            "account": {
              "address": "ST3QS01894F67ZQ9V4WQEVC3P0YPVAMGQPXF71YQJ"
            },
            "amount": {
              "value": "6000000000000",
              "currency": {
                "decimals": 6,
                "symbol": "STX"
              }
            },
            "metadata": {
              "tx_id": "0x915f99fb8f37df9480a9ce88a98619e1c450327cb21013e514d1d077a73cf62e"
            }
          },
          {
            "operation_identifier": {
              "index": 6
            },
            "type": "stx_unlock",
            "status": "success",
            "account": {
              "address": "ST33DR7DBHWGT4Z7F1M1KB4KERY99SFNE0RMPZVE5"
            },
            "amount": {
              "value": "6167000000000",
              "currency": {
                "decimals": 6,
                "symbol": "STX"
              }
            },
            "metadata": {
              "tx_id": "0xf1266013ff6b0dbae07d9f7fbaa5aa3773dd634dc15b43877ae4d0bcabcc884e"
            }
          }
```

Note how `transaction_identifier.hash` matches the first operation's `metadata.tx_id`:
```
        "transaction_identifier": {
          "hash": "0x7cfac55147759a14d163bd96b89138df090dd730df5fa5c34a086011b5e9621e"
        },

```

```
        "metadata": {
          "tx_id": "0x7cfac55147759a14d163bd96b89138df090dd730df5fa5c34a086011b5e9621e"
        }
```

But when you try to look up transaction hash `0x7cfac55147759a14d163bd96b89138df090dd730df5fa5c34a086011b5e9621e` on `block/transaction`, the transaction returned is the transaction for the stacking (that happened in [block 5757](https://explorer.stacks.co/txid/0x7cfac55147759a14d163bd96b89138df090dd730df5fa5c34a086011b5e9621e?chain=testnet)).
```
{
  "transaction_identifier": {
    "hash": "0x7cfac55147759a14d163bd96b89138df090dd730df5fa5c34a086011b5e9621e"
  },
  "operations": [
    {
      "operation_identifier": {
        "index": 0
      },
      "type": "fee",
      "status": "success",
      "account": {
        "address": "ST3C4YVASFG37P8E6210J9KHZJB4MF8ZRBQFKH41N"
      },
      "amount": {
        "value": "-260",
        "currency": {
          "decimals": 6,
          "symbol": "STX"
        }
      }
    },
    {
      "operation_identifier": {
        "index": 1
      },
      "type": "stack_stx",
      "status": "success",
      "account": {
        "address": "ST3C4YVASFG37P8E6210J9KHZJB4MF8ZRBQFKH41N"
      },
      "metadata": {
        "lock_period": "1",
        "amount_ustx": "5140000000000",
        "start_burn_height": "2065169",
        "unlock_burn_height": "2067200",
        "stacker_address": "ST3C4YVASFG37P8E6210J9KHZJB4MF8ZRBQFKH41N",
        "pox_addr": "mmPKhbTX4mM4R6LAJDfq3yaRR2WHs6XkJS"
      }
    },
    {
      "operation_identifier": {
        "index": 2
      },
      "type": "stx_lock",
      "status": "success",
      "account": {
        "address": "ST3C4YVASFG37P8E6210J9KHZJB4MF8ZRBQFKH41N"
      },
      "amount": {
        "value": "-5140000000000",
        "currency": {
          "decimals": 6,
          "symbol": "STX"
        }
      },
      "metadata": {
        "locked": "5140000000000",
        "unlock_height": "2067200"
      }
    }
  ]
}
```

## Request
Could the protocol be able to incorporate an actual on-chain event for the token unlock?
Or if not, could the "forged" transaction use a brand new transaction hash (that only Rosetta would use). The caveat to that would be there still could be a conflict if a future block mined by chance uses that transaction hash in one of the transactions.

### PR DESCRIPTION
**Pull request by asimm241**
## Description
This pr fixes the conflicting hash problem. The `stx_lock` transaction hash was conflicting with `stx_unlock` transactions. Now,  `stx_unlock` uses `coinbase` transaction hash.  

closes #760 

## Type of Change
- [ ] New feature
- [x] Bug fix
- [ ] API reference/documentation update
- [ ] Other

## Testing information
Updated integration test to check this scenerio

## Checklist
- [x] Code is commented where needed
- [x] Unit test coverage for new or modified code paths
- [x] `npm run test` passes
- [ ] Changelog is updated
- [x] @zone117x for review

### CODE REVIEW

File: src/datastore/postgres-store.ts [hunk 1]
```diff
@@ -5860,9 +5860,10 @@ export class PgDataStore
       tx_id: Buffer;
     }>(
       `
-      SELECT locked_amount, unlock_height, block_height, tx_id, locked_address
-      FROM stx_lock_events
-      WHERE canonical = true AND unlock_height <= $1 AND unlock_height > $2
+      SELECT locked_amount, unlock_height, sle.block_height, locked_address, txs.tx_id
+      FROM stx_lock_events sle inner JOIN txs ON (sle.unlock_height = txs.block_height)
```
Comment (zone117x) [inline src/datastore/postgres-store.ts:5864]: It looks like `sle.unlock_height` is referring to the burnblock (btc) height whereas `txs.block_height` is referring to Stacks block height, so this JOIN won't work correctly

File: src/tests-rosetta/api.ts [hunk 2]
```diff
@@ -2671,19 +2671,31 @@ describe('Rosetta API', () => {
...
+    }
+
     const query1 = await supertest(api.address)
       .post(`/rosetta/v1/block`)
       .send({
         network_identifier: { blockchain: 'stacks', network: 'testnet' },
         block_identifier: { hash: block.result.block_hash },
       });
+
+      console.log('there you go4');
```
Comment (rafaelcr) [inline src/tests-rosetta/api.ts:2698]: I think this debug log might have slipped through 👀

File: src/datastore/postgres-store.ts (hunk 1 above)
Comment (asimm241) [reply src/datastore/postgres-store.ts:5864]: oh, in that case probably need another join.

**Review by rafaelcr — APPROVED** [review]
LGTM but I'd wait for @zone117x 's review just to be sure since he has way more context than me on this particular issue

File: src/datastore/postgres-store.ts [hunk 3]
```diff
@@ -5860,11 +5860,12 @@ export class PgDataStore
       tx_id: Buffer;
     }>(
       `
-      SELECT locked_amount, unlock_height, block_height, tx_id, locked_address
-      FROM stx_lock_events
-      WHERE canonical = true AND unlock_height <= $1 AND unlock_height > $2
+      SELECT locked_amount, unlock_height, sle.block_height, locked_address, txs.tx_id
+      FROM stx_lock_events sle INNER JOIN txs ON ($3 = txs.block_height)
```
Comment (zone117x) [inline src/datastore/postgres-store.ts:5864]: I'm having a hard time reasoning about the correctness of this query, and we don't have tests that demonstrate much of the Stacks vs Bitcoin block height differences that the `unlock_height <= $1 AND unlock_height > $2` statement is responsible for. 

It looks like there's at least one issue here where the `txs` rows are not checked for `canonical = true AND microblock_canonical = true`. Perhaps it makes sense to preserve the original query, and create a new one to grab the correct coinbase tx?

**Review by zone117x — APPROVED** [review]
LGTM thanks @asimm241!
